// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocaptionController from "./autocaption_controller"
import TextToSpeechController from "./text_to_speech_controller"
application.register("autocaption", AutocaptionController)
application.register("text-to-speech", TextToSpeechController)
